--------------------------------------------------------
--  File created - Sunday-March-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "OLS655_181B23"."CLIENT" 
   (	"CLIENT_ID" NUMBER(8,0), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"PROVINCE" VARCHAR2(20 BYTE), 
	"POSTAL_CODE" VARCHAR2(6 BYTE), 
	"PHONE_NUMBER" VARCHAR2(10 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER_DATA" ;
REM INSERTING into OLS655_181B23.CLIENT
SET DEFINE OFF;
Insert into OLS655_181B23.CLIENT (CLIENT_ID,FIRST_NAME,LAST_NAME,ADDRESS,CITY,PROVINCE,POSTAL_CODE,PHONE_NUMBER,EMAIL) values (10000026,'dd','ff',null,null,'AB',null,null,null);
Insert into OLS655_181B23.CLIENT (CLIENT_ID,FIRST_NAME,LAST_NAME,ADDRESS,CITY,PROVINCE,POSTAL_CODE,PHONE_NUMBER,EMAIL) values (10000041,'eric','yu','12','qq','ON','ff','3','ee');
--------------------------------------------------------
--  DDL for Index CLIENT_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLS655_181B23"."CLIENT_ID_PK" ON "OLS655_181B23"."CLIENT" ("CLIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER_DATA" ;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "OLS655_181B23"."CLIENT" MODIFY ("FIRST_NAME" CONSTRAINT "CLIENT_FIRST_NAME_NN" NOT NULL ENABLE);
  ALTER TABLE "OLS655_181B23"."CLIENT" MODIFY ("CLIENT_ID" CONSTRAINT "CLIENT_ID_NN" NOT NULL ENABLE);
  ALTER TABLE "OLS655_181B23"."CLIENT" ADD CONSTRAINT "CLIENT_ID_PK" PRIMARY KEY ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER_DATA"  ENABLE;
  ALTER TABLE "OLS655_181B23"."CLIENT" MODIFY ("LAST_NAME" CONSTRAINT "CLIENT_LAST_NAME_NN" NOT NULL ENABLE);
